pool:
  vmImage: ubuntu-latest

name: $(BuildID)-$(Build.SourceBranchName)

stages:
- stage: Build
  jobs:
  - job: BuildAll
    steps:
    - powershell: ./ci_build.ps1
    - publish: WebClient/deploy
      artifact: web-client-build
    - publish: Server/deploy
      artifact: server-build