version: '3.8'

services:
  server:
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 70M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
